In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"D:\search _engine\clean_movies.csv")

In [3]:
df

,Title,Director,Cast,Year,Language,movie_info
0,Tungabhadra,Srinivas Gogineni,"Adith Arun, Dimple Chopade",2015,Telugu,Movie Title: Tungabhadra. Directed by: Sriniva...
1,Tej I Love You,A. Karunakaran,"Sai Dharam Tej, Anupama Parameswaran, Surekha ...",2018,Telugu,Movie Title: Tej I Love You. Directed by: A. K...
2,RX 100,Ajay Bhupathi,"Karthikeya, Payal Rajput, Rao Ramesh, Ramki",2018,Telugu,Movie Title: RX 100. Directed by: Ajay Bhupath...
3,Vijetha,Rakesh Shashii,"Kalyaan Dhev, Malavika Nair, Murali Sharma, Na...",2018,Telugu,Movie Title: Vijetha. Directed by: Rakesh Shas...
4,Aatagadharaa Siva,Chandra Siddhartha,"Uday Shankar, Doddanna, Hyper Aadi, Chammak Ch...",2018,Telugu,Movie Title: Aatagadharaa Siva. Directed by: C...
...,...,...,...,...,...,...
2691,NaN,NaN,NaN,2016,Telugu,Movie Title: . Directed by: . Starring: . Rele...
2692,NaN,NaN,NaN,2021,Telugu,Movie Title: . Directed by: . Starring: . Rele...
2693,NaN,NaN,NaN,2007,Telugu,Movie Title: . Directed by: . Starring: . Rele...
2694,NaN,NaN,NaN,2023,Telugu,Movie Title: . Directed by: . Starring: . Rele...
2695,NaN,NaN,NaN,2013,Telugu,Movie Title: . Directed by: . Starring: . Rele...

In [4]:
# Basic Information

print("Dataset Shape :", df.shape)

df.head()

Dataset Shape : (2696, 6)

,Title,Director,Cast,Year,Language,movie_info
0,Tungabhadra,Srinivas Gogineni,"Adith Arun, Dimple Chopade",2015,Telugu,Movie Title: Tungabhadra. Directed by: Sriniva...
1,Tej I Love You,A. Karunakaran,"Sai Dharam Tej, Anupama Parameswaran, Surekha ...",2018,Telugu,Movie Title: Tej I Love You. Directed by: A. K...
2,RX 100,Ajay Bhupathi,"Karthikeya, Payal Rajput, Rao Ramesh, Ramki",2018,Telugu,Movie Title: RX 100. Directed by: Ajay Bhupath...
3,Vijetha,Rakesh Shashii,"Kalyaan Dhev, Malavika Nair, Murali Sharma, Na...",2018,Telugu,Movie Title: Vijetha. Directed by: Rakesh Shas...
4,Aatagadharaa Siva,Chandra Siddhartha,"Uday Shankar, Doddanna, Hyper Aadi, Chammak Ch...",2018,Telugu,Movie Title: Aatagadharaa Siva. Directed by: C...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2696 entries, 0 to 2695
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       2676 non-null   object
 1   Director    2592 non-null   object
 2   Cast        2652 non-null   object
 3   Year        2696 non-null   int64
 4   Language    2696 non-null   object
 5   movie_info  2696 non-null   object
dtypes: int64(1), object(5)
memory usage: 126.5+ KB

In [6]:
df['movie_info'][0]

'Movie Title: Tungabhadra. Directed by: Srinivas Gogineni. Starring: Adith Arun, Dimple Chopade. Released in: 2015.'

In [7]:
# Check Missing Values

df.isnull().sum()

Title          20
Director      104
Cast           44
Year            0
Language        0
movie_info      0
dtype: int64

In [8]:
# Check Duplicate Rows

print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [9]:
df.columns

Index(['Title', 'Director', 'Cast', 'Year', 'Language', 'movie_info'], dtype='object')

In [53]:
# Handle Missing Values

df["Title"] = df["Title"].fillna("unknown")
df["Director"] = df["Director"].fillna("unknown")
df["Cast"] = df["Cast"].fillna("unknown")

In [54]:
df.isnull().sum()

Title         0
Director      0
Cast          0
Year          0
Language      0
movie_info    0
dtype: int64

In [12]:
# Create a meaningful text representation for each movie

df["movie_info"] = (
    "Movie Title: " + df["Title"] + ". " +
    "Directed by: " + df["Director"] + ". " +
    "Starring: " + df["Cast"] + ". " +
    "Released in: " + df["Year"].astype(str) + "."
)

In [13]:
df[["Title", "movie_info"]].head(5)

               Title                                         movie_info
0        Tungabhadra  Movie Title: Tungabhadra. Directed by: Sriniva...
1     Tej I Love You  Movie Title: Tej I Love You. Directed by: A. K...
2             RX 100  Movie Title: RX 100. Directed by: Ajay Bhupath...
3            Vijetha  Movie Title: Vijetha. Directed by: Rakesh Shas...
4  Aatagadharaa Siva  Movie Title: Aatagadharaa Siva. Directed by: C...

In [14]:
df["movie_info"].isnull().sum()

0

In [15]:
df.to_csv(r'movies_dataset.csv', index=False)

Embeddings & FAISS

In [16]:
# Import Required Libraries

import numpy as np
import pandas as pd
import faiss

from sentence_transformers import SentenceTransformer

In [194]:
# Load Clean Dataset

df=pd.read_csv(r"movies_dataset.csv")

print("Total Movies :", len(df))

Total Movies : 2696

In [17]:
df.isnull().sum()

Title         0
Director      0
Cast          0
Year          0
Language      0
movie_info    0
dtype: int64

In [196]:
df.to_csv(r"movies.csv", index=False)

In [18]:
# Load SBERT Model

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Model Loaded Successfully")

Model Loaded Successfully

In [19]:
# Generate Embeddings

movie_embeddings = model.encode(
    df["movie_info"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/85 [00:00<?, ?it/s]

In [20]:
print("Embedding Shape :", movie_embeddings.shape)

print("Data Type :", movie_embeddings.dtype)

Embedding Shape : (2696, 384)
Data Type : float32

In [21]:
# Save Embeddings

np.save("movie_embeddings.npy", movie_embeddings)

print("Embeddings Saved Successfully")

Embeddings Saved Successfully

In [22]:
movie_embeddings = np.load("movie_embeddings.npy")

print(movie_embeddings.shape)

(2696, 384)

In [23]:
#Normalize Embeddings

faiss.normalize_L2(movie_embeddings)

In [24]:
#Create FAISS Index

dimension = movie_embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

In [25]:
#Add Movie Embeddings

index.add(movie_embeddings)

print("Movies Indexed :", index.ntotal)

Movies Indexed : 2696

In [26]:
#Save FAISS Index

faiss.write_index(index, "movie.index")

print("FAISS Index Saved Successfully")

FAISS Index Saved Successfully

In [27]:
#Verify Saved Index
loaded_index = faiss.read_index("movie.index")

print("Indexed Movies :", loaded_index.ntotal)

Indexed Movies : 2696

Semantic Search Engine

In [28]:
# Load FAISS Index

index = faiss.read_index("movie.index")

In [29]:
# Load SBERT Model

model = SentenceTransformer("all-MiniLM-L6-v2")

In [30]:
# Verify Everything

print("Movies :", len(df))
print("Embeddings :", movie_embeddings.shape)
print("Indexed Movies :", index.ntotal)

Movies : 2696
Embeddings : (2696, 384)
Indexed Movies : 2696

In [31]:
# Query Preprocessing

def preprocess_query(query):

    query = query.lower()

    query = " ".join(query.split())

    return query

In [32]:
# Convert Query to Embedding

def get_query_embedding(query):

    query = preprocess_query(query)

    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )

    faiss.normalize_L2(query_embedding)

    return query_embedding

In [33]:
# Search Function

def search_movies(query, top_k=3):

    query_embedding = get_query_embedding(query)

    scores, indices = index.search(query_embedding, top_k)

    results = df.iloc[indices[0]].copy()

    results["Similarity Score"] = scores[0].round(3)

    return results.reset_index(drop=True)

In [34]:
# Test Search

search_movies("Bahubali")

,Title,Director,Cast,Year,Language,movie_info,Similarity Score
0,Baahubali: The Beginning,S.S. Rajamouli,"Prabhas, Rana, Tamannaah, Anushka Shetty, Saty...",2015,Telugu,Movie Title: Baahubali: The Beginning. Directe...,0.622
1,Baahubali: The Conclusion,S. S. Rajamouli,"Prabhas, Anushka Shetty, Ramya Krishna, Rana D...",2017,Telugu,Movie Title: Baahubali: The Conclusion. Direct...,0.610
2,Babloo,Ravichandran Reddy,"Mano Tej, Aditi Sharma, Mukul Dev",2011,Telugu,Movie Title: Babloo. Directed by: Ravichandran...,0.587

In [35]:
search_movies("Prabhas")

,Title,Director,Cast,Year,Language,movie_info,Similarity Score
0,Aavu Puli Madhyalo Prabhas Pelli,Ravi Pachipala,"Kalakeya Prabhakar, Ravi Teja, Ashwini Chandra...",2016,Telugu,Movie Title: Aavu Puli Madhyalo Prabhas Pelli....,0.480
1,Prabhanjanam,Bhaskara Rao Vendrati,"Ajmal Ameer, Sandesh, Aarushi, Panchi Bora, Na...",2014,Telugu,Movie Title: Prabhanjanam. Directed by: Bhaska...,0.477
2,Pranaya Veedhullo,Prabhakar Jaini,"Dr. K. V. Ramanachari, Suresh Chandra, Vamshi ...",2013,Telugu,Movie Title: Pranaya Veedhullo. Directed by: P...,0.459

In [36]:
search_movies("Rajamouli")

,Title,Director,Cast,Year,Language,movie_info,Similarity Score
0,Rajababu,Muppalaneni Shiva,"Rajasekhar, Brahmanandam, Kondavalasa Lakshman...",2006,Telugu,Movie Title: Rajababu. Directed by: Muppalanen...,0.572
1,Rajahmundry ki 50 km duramloo,Vijay Surya,"Hemanth, Nairuthi,",2015,Telugu,Movie Title: Rajahmundry ki 50 km duramloo. Di...,0.503
2,Express Raja,Merlapaka Gandhi,"Sharwanand, Surabhi, Harish Uthaman",2016,Telugu,Movie Title: Express Raja. Directed by: Merlap...,0.502

In [37]:
search_movies("Mahesh Babu")

,Title,Director,Cast,Year,Language,movie_info,Similarity Score
0,Mohabbat Mein,Mahesh Surya,"Karthik, Hamida",2016,Telugu,Movie Title: Mohabbat Mein. Directed by: Mahes...,0.524
1,Brahmotsavam,Srikanth Addala,"Mahesh Babu, Kajal Aggarwal, Samantha Ruth Pra...",2016,Telugu,Movie Title: Brahmotsavam. Directed by: Srikan...,0.513
2,Maa Idhari Madhya,Ramesh Maddineni,"Bharat, Vidisha, Brahmanandam",2006,Telugu,Movie Title: Maa Idhari Madhya. Directed by: R...,0.506

Hybrid Search

In [38]:
%pip install rapidfuzz

Requirement already satisfied: rapidfuzz in d:\search _engine\search\Lib\site-packages (3.14.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:

# Semantic Movie Recommendation Engine
# Hybrid Search


import re
import faiss
import numpy as np
import pandas as pd

from rapidfuzz import fuzz
from rapidfuzz import process

from sentence_transformers import SentenceTransformer

In [40]:
print("Movies :", len(df))
print("Embeddings :", movie_embeddings.shape)
print("Indexed Movies :", index.ntotal)

Movies : 2696
Embeddings : (2696, 384)
Indexed Movies : 2696

In [41]:
def preprocess_query(query):

    query = query.lower()

    query = query.strip()

    query = re.sub(r"\s+", " ", query)

    return query

In [42]:
preprocess_query("   BAHUBALI     ")

'bahubali'

In [43]:
# Fuzzy Title Search# Create a list of movie titles

movie_titles = df["Title"].fillna("").tolist()

In [44]:
# Test RapidFuzz

process.extract(
    "bahubali",
    movie_titles,
    scorer=fuzz.WRatio,
    limit=5
)

[('Baahubali: The Beginning', 78.75, 469),
 ('Baahubali: The Conclusion', 78.75, 533),
 ('Baahubali 2: The Conclusion', 78.75, 2664),
 ('Kali', 77.14285714285715, 872),
 ('Kalki', 67.5, 316)]

In [45]:
# Build the function

def fuzzy_title_search(query, limit=3):

    query = preprocess_query(query)

    matches = process.extract(
        query,
        movie_titles,
        scorer=fuzz.WRatio,
        limit=limit
    )

    results = []

    for title, score, idx in matches:

        results.append({
            "Index": idx,
            "Title": title,
            "Title Score": score / 100
        })

    return pd.DataFrame(results)

In [46]:
fuzzy_title_search("bahubali")

   Index                        Title  Title Score
0    469     Baahubali: The Beginning       0.7875
1    533    Baahubali: The Conclusion       0.7875
2   2664  Baahubali 2: The Conclusion       0.7875

In [47]:
fuzzy_title_search("pushpa")

   Index               Title  Title Score
0    912  Pushpa 2: The Rule         0.75
1   1085    Pushpa: The Rise         0.75
2   1092    Pushpaka Vimanam         0.75

In [48]:
def semantic_search(query, limit=10):

    query = preprocess_query(query)

    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )

    faiss.normalize_L2(query_embedding)

    scores, indices = index.search(query_embedding, limit)

    results = pd.DataFrame({
        "Index": indices[0],
        "Semantic Score": scores[0]
    })

    return results

In [49]:
semantic_search("bahubali")

   Index  Semantic Score
0    469        0.621726
1    533        0.610433
2   2513        0.586620
3   2664        0.579441
4    869        0.566249
5   2087        0.558284
6   2627        0.553598
7   2541        0.548671
8   2298        0.523702
9   1775        0.511961

def hybrid_search(query, limit=3):

    title_results = fuzzy_title_search(query, limit)

    semantic_results = semantic_search(query, limit)

    results = pd.merge(
        title_results,
        semantic_results,
        on="Index",
        how="outer"
    )

    results["Title Score"] = results["Title Score"].fillna(0)

    results["Semantic Score"] = results["Semantic Score"].fillna(0)

    return results

In [52]:
hybrid_search("bahubali")

   Index                        Title  Title Score  Semantic Score
0    469     Baahubali: The Beginning       0.7875        0.621726
1    533    Baahubali: The Conclusion       0.7875        0.610433
2   2513                          NaN       0.0000        0.586620
3   2664  Baahubali 2: The Conclusion       0.7875        0.000000

def hybrid_search(query, limit=20):

    title_results = fuzzy_title_search(query, limit)
    semantic_results = semantic_search(query, limit)

    title_results = title_results[["Index", "Title Score"]]
    semantic_results = semantic_results[["Index", "Semantic Score"]]

    results = pd.merge(
        title_results,
        semantic_results,
        on="Index",
        how="outer"
    )

    results["Title Score"] = results["Title Score"].fillna(0)
    results["Semantic Score"] = results["Semantic Score"].fillna(0)

    results["Final Score"] = (
        0.60 * results["Title Score"] +
        0.40 * results["Semantic Score"]
    )

    results = results.sort_values(
        "Final Score",
        ascending=False
    )

    results = results.head(3)

    results["Title"] = df.iloc[results["Index"]]["Title"].values

    return results.reset_index(drop=True)

In [56]:
hybrid_search("bahubali")

,Index,Title Score,Semantic Score,Final Score,Title
0,469,0.7875,0.621726,0.721190,Baahubali: The Beginning
1,533,0.7875,0.610433,0.716673,Baahubali: The Conclusion
2,2664,0.7875,0.579441,0.704277,Baahubali 2: The Conclusion

In [58]:
def hybrid_search(query, limit=50):

    title_results = fuzzy_title_search(query, limit)
    semantic_results = semantic_search(query, limit)

    title_results = title_results[["Index", "Title Score"]]
    semantic_results = semantic_results[["Index", "Semantic Score"]]

    results = pd.merge(
        title_results,
        semantic_results,
        on="Index",
        how="outer"
    )

    results["Title Score"] = results["Title Score"].fillna(0)
    results["Semantic Score"] = results["Semantic Score"].fillna(0)

    results["Final Score"] = (
        0.60 * results["Title Score"] +
        0.40 * results["Semantic Score"]
    )

    results = results.sort_values(
        "Final Score",
        ascending=False
    )

    results = results.head(3)

    results["Title"] = df.iloc[results["Index"]]["Title"].values
    results["Year"] = df.iloc[results["Index"]]["Year"].values

    results = results[["Title", "Year"]]

    return results.reset_index(drop=True)

In [61]:
hybrid_search("bahubali")

                         Title  Year
0     Baahubali: The Beginning  2015
1    Baahubali: The Conclusion  2017
2  Baahubali 2: The Conclusion  2017